In [14]:
import torch 

In [11]:
t0 = torch.tensor([10.], requires_grad=True)
t1 = torch.tensor([12.], requires_grad=True)
t2 = torch.tensor([-15.], requires_grad=True)
t4 = t0 * t1 + t2
t4


tensor([105.], grad_fn=<AddBackward0>)

In [12]:
t4.backward()

In [13]:
t0.grad, t1.grad, t2.grad

(tensor([12.]), tensor([10.]), tensor([1.]))

In [25]:
a = lemur.tensor([[10.,12.],[-1.,-4.]], requires_grad = True)
b = lemur.rand_like(a)
c = (a @ b).mean()
c.backward()
a.grad

tensor([[0.4100, 0.2642],
        [0.4100, 0.2642]])

In [26]:
c

tensor(5.8041, grad_fn=<MeanBackward0>)

In [ ]:
a = lemur.tensor([...], requires_grad = True)
b = lemur.tensor([...], requires_grad = True)
c = (a + b).relu()